version: '3.9'

services:

  #php+apache
  php:
    image: harbor.infrastructure.sicredipioneira.com.br/pioneira-common/php:8.1-apache2.4
    container_name: contactpro_backend
    working_dir: /var/www/html/
    depends_on:
      - mysql
      - redis
    networks:
      - contactpro_network
    ports:
      - "4080:80"
    volumes:
      - "./backend:/var/www/html"
      - "./apache/sites-enabled/:/etc/apache2/sites-enabled/"
    environment:
      FRONTEND_HOST: node:4080
      MYSQL_HOST: mysql
      MYSQL_PASSWORD: user
      MYSQL_USER: user
      MYSQL_DATABASE: contactpro_database
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: senha

  #node
  node:
    image: harbor.infrastructure.sicredipioneira.com.br/pioneira-common/vuejs:2-node16
    container_name: contactpro_frontend
    working_dir: /home/node/app
    stdin_open: true
    tty: true
    command: bash -c "npm i && npm run serve"
    networks:
      - contactpro_network
    ports:
      - "4081:8080"
    volumes:
      - "./frontend:/home/node/app"
      - "../packages/Pioneira/Ui/src/lib:/pioneira-ui"
    environment:
      BACK_HOST: php:4081/api
      CHOKIDAR_USEPOLLING: 'true'

  #mysql
  mysql:
    image: mysql:8.0
    container_name: contactpro_database
    networks:
      - contactpro_network
    ports:
      - "3306:3306"
    volumes:
      # - "./db:/home/bkp"
      - "mysql_db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_HOST: '0.0.0.0'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: user
      MYSQL_USER: user
      MYSQL_DATABASE: contactpro_database

  #phpmyadmin
  dbadmin:
    image: phpmyadmin/phpmyadmin
    restart: "no"
    container_name: contactpro_phpmyadmin
    networks:
      - contactpro_network
    ports:
      - "4034:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

  #redis
  redis:
    image: redis:7.0
    container_name: contactpro_session_database
    command: bash -c "redis-server --requirepass senha"
    networks:
      - contactpro_network
    ports:
      - "6379:6379"
    volumes:
      - "redis_db:/data"

  #redis-commander
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: contactpro_redis-commander
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=senha
    ports:
      - "8083:8081"
    networks:
      - contactpro_network

volumes:
  mysql_db:
    driver: "local"
  redis_db:
    driver: "local"

networks:
  contactpro_network:
    driver: bridge
